database:
  host: localhost
  port: 3307
  user: fake
  password: fake
  database: fake

api:
  openai: fake
  openai-org: fake
  pinecone: fake
  pinecone-name: db-chatbot-personal
  embedding-model: text-embedding-ada-002
